# Generated by Django 2.2.3 on 2019-08-05 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password2',
        ),
    ]
