# Generated by Django 2.2.3 on 2019-08-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190805_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phne',
            new_name='phone',
        ),
    ]
