# Generated by Django 2.2.3 on 2019-08-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disposal', '0004_auto_20190803_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposal',
            name='writer',
        ),
    ]
