# Generated by Django 2.2.3 on 2019-08-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposal', '0005_remove_disposal_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposal',
            name='writer',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
