# Generated by Django 2.2.3 on 2019-08-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposal', '0006_disposal_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposal',
            name='photo',
            field=models.ImageField(upload_to='image'),
        ),
    ]
