# Generated by Django 2.2.3 on 2019-08-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disposal', '0007_auto_20190809_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposal',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
