# Generated by Django 2.2.3 on 2019-08-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='phone',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
