# Generated by Django 2.2.3 on 2019-08-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='writer',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
