# Generated by Django 2.2.3 on 2019-08-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_comment_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='writer',
        ),
    ]
