# Generated by Django 2.2.3 on 2019-08-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_comment_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='address',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
