# Generated by Django 2.2.3 on 2019-08-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_board_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='address',
        ),
    ]
